### ISSUE TITLE
How to access request header variables?

### ISSUE THREAD

**Issue by ajaypandit** [jenkinsci/generic-webhook-trigger-plugin#18]
I am trying to access request header variable, X-GitHub-Event,  but is always coming up as null. Here is the snippet of my code to extract 'event' variable from header but is not working:

properties([
    pipelineTriggers([
      [$class: 'GenericTrigger',
        genericVariables: [
          [expressionType: 'JSONPath', key: 'owner', value: '$.repository.owner.login'],
          [expressionType: 'JSONPath', key: 'repo', value: '$.repository.name'],
          [expressionType: 'JSONPath', key: 'username', value: '$.sender.login']
        ],
        genericHeaderVariables: [
          [key: 'event', regexpFilter: '/X-GitHubEvent:(.*)/g']
        ],
        regexpFilterText: '',   
        regexpFilterExpression: ''
      ]
    ])
  ])

**Comment by tomasbjerre** [comment]
You probably want to have an empty string as regexp.

**Comment by ajaypandit** [comment]
I am still getting it as null even though the X-GitHub-Event is set to 'release'.

**Comment by tomasbjerre** [comment]
If I create a job with this header configured:
```
X-GitHub-Event
```

And invoke Jenkins with:
```
curl -vs -H "X-GitHub-Event: aadsasd123" http://admin:admin@localhost:8080/jenkins/generic-webhook-trigger/invoke 2>&1
```

I get this in the log:
```
Contributing variables:

    X_GitHub_Event_0 = aadsasd123
    X_GitHub_Event = aadsasd123
```

**Comment by tomasbjerre** [comment]
I corrected the title/description in the GUI now. It was very much incorrect and fixed in: https://github.com/jenkinsci/generic-webhook-trigger-plugin/commit/2643526ce361183d2f47933c705ae7278d50f194

**Comment by ajaypandit** [comment]
The key has 'dashes' while the variable as 'underscores'. Is that correct? Are there two variables, one with "_0" suffix and one without?

I have following genericHeaderVariables and headers, but the variable is still not coming as contributing variable.

genericHeaderVariables: [
          [key: 'X-GitHub-Event', regexpFilter: '']
        ]

Headers:

X-GitHub-Event: release

**Comment by tomasbjerre** [comment]
Actually, the field is not the "variable name". That was an documentation bug that is now fixed.
The field is the header name, so `X-GitHub-Event` is correct.

And yes, 2 variables are created with same value.

In your case it is probably convenient to use the one without `_0`. In other cases where there are actually several matches then using variables `_0`, `_1`... might be more convenient.

**Comment by ajaypandit** [comment]
We can't use X-GitHub-Event as it is not a valid variable name (has hyphens in it).

**Comment by tomasbjerre** [comment]
Yes, that is why the header name will be transformed to a valid variable name. The header `X-GitHub-Event` becomes a variable named `X_GitHub_Event`.

**Comment by ajaypandit** [comment]
I am still getting X_GitHub_Event as null.

**Comment by tomasbjerre** [comment]
Can you reproduce that with a curl command? If you do `curl -vs -H "X-GitHub-Event: aadsasd123" ... ` do you still get this?
```
Contributing variables:

    X_GitHub_Event_0 = null
    X_GitHub_Event = null
```

**Comment by tomasbjerre** [comment]
I added a more detailed example with headers and multibranch pipeline in the readme.

**Comment by ajaypandit** [comment]
No, I don't get any contributing variable when I try this:

curl -vs -H "X-GitHub-Event: aadsasd123" http://<user>:<password>@jenkins-host:8080/generic-webhook-trigger/invoke

I do get 200 response back with the expected results but no contributing variables output.

**Comment by tomasbjerre** [comment]
And you did rescan the multibranch pipeline?

You may check the jobs being build, the sub-jobs/branches. Check that their configuration has been updated according to the multibranch pipeline.

And as a last resort, remove the entire multibranch pipeline and create it again from the same jenkinsfile. To make absolutely sure it is using the jenkinsfile.

**Comment by tomasbjerre** [comment]
I create a multibranch job like this:

![screen1](https://user-images.githubusercontent.com/439571/29238547-362b2204-7f38-11e7-9c2d-f3a5fd08eaab.png)

And after creation the master branch will look like this:

![screen2](https://user-images.githubusercontent.com/439571/29238550-449c86b6-7f38-11e7-8667-b910aadb8808.png)

I trigger it with: `curl -vs -H "X-GitHub-Event: aadsasd123" http://:@jenkins-host:8080/generic-webhook-trigger/invoke`

And the master job will run and have this in the log:

![screen3](https://user-images.githubusercontent.com/439571/29238553-587fe2e0-7f38-11e7-9b90-8f7e8221ad95.png)

**Comment by tomasbjerre** [comment]
This might actually be same as #20 fixed by #21 .
